version: "3.7"
services:
  api:
    build:
      context: api
    ports:
      - 80:80
    volumes:
      - type: bind
        source: ${PWD}/api
        target: /api
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    environment:
      - PWD=$PWD
      - REDIS_PASS=$REDIS_PASS
      - MONGODB_USER=$MONGODB_USER
      - MONGODB_PASS=$MONGODB_PASS
    networks:
      server-network:

  remove_users:
    build:
      context: utils
    environment:
      - MONGODB_USER=$MONGODB_USER
      - MONGODB_PASS=$MONGODB_PASS
    command: python3 create_admin.py remove
    depends_on:
      - mongodb
      - api
    networks:
      server-network:

  create_users:
    build:
      context: utils
    environment:
      - MONGODB_USER=$MONGODB_USER
      - MONGODB_PASS=$MONGODB_PASS
    command: python3 create_admin.py create
    depends_on:
      - mongodb
      - api
      - remove_users
    networks:
      server-network:

  mongodb:
    image: mongo:4.4.1
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGODB_USER
      MONGO_INITDB_ROOT_PASSWORD: $MONGODB_PASS
    volumes:
      - $PWD/data:/data/db
    networks:
      server-network:

networks:
  server-network:
    external: false
    name: server-network