version: "3.7"
services:
  waf:
    image: owasp/modsecurity-crs:3.3-nginx
    ports:
      - 443:443
    volumes:
      - ./modsecurity/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./modsecurity/cert.pem:/etc/nginx/conf/cert.pem
      - ./modsecurity/key.pem:/etc/nginx/conf/key.pem
    networks:
      main-network:

  api:
    build:
      context: api
    ports:
      - 80:80
    volumes:
      - type: bind
        source: ${PWD}/api
        target: /api
    environment:
      - REDIS_PASS=$REDIS_PASS
      - MONGODB_USER=$MONGODB_USER
      - MONGODB_PASS=$MONGODB_PASS

  remove_users:
    build:
      context: utils
    environment:
      - MONGODB_USER=$MONGODB_USER
      - MONGODB_PASS=$MONGODB_PASS
    command: python3 create_admin.py remove
    depends_on:
      - mongodb
      - api
    networks:
      main-network:

  create_users:
    build:
      context: utils
    environment:
      - MONGODB_USER=$MONGODB_USER
      - MONGODB_PASS=$MONGODB_PASS
    command: python3 create_admin.py create
    depends_on:
      - mongodb
      - api
      - remove_users
    networks:
      main-network:

  mongodb:
    image: mongo:4.4.1
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGODB_USER
      MONGO_INITDB_ROOT_PASSWORD: $MONGODB_PASS
    volumes:
      - ./data:/data/db
    networks:
      main-network:

  openvpn:
    build:
      context: ovpn-admin
      dockerfile: Dockerfile.openvpn
    image: openvpn:local
    command: /etc/openvpn/setup/configure.sh
    cap_add:
      - NET_ADMIN
    ports:
      - 7777:1194 # for openvpn
      - 8080:8080 # for ovpn-admin because of network_mode
    volumes:
      - ./easyrsa_master:/etc/openvpn/easyrsa
      - ./ccd_master:/etc/openvpn/ccd
    networks:
      main-network:
      vpn-network:

  ovpn-admin:
    build:
      context: ovpn-admin
    image: ovpn-admin:local
    command: /app/ovpn-admin --debug --ovpn.network="172.16.100.0/22" --master.sync-token="TOKEN" --easyrsa.path="/mnt/easyrsa" --easyrsa.index-path="/mnt/easyrsa/pki/index.txt" --ovpn.server="127.0.0.1:7777:tcp"
    network_mode: service:openvpn
    volumes:
      - ./easyrsa_master:/mnt/easyrsa
      - ./ccd_master:/mnt/ccd


  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    networks:
      main-network:

  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yaml
    ports:
      - 3000:3000
    networks:
      main-network:

  test_vpn:
    image: dontrebootme/microbot:v1
    expose:
      - 80
    networks:
      vpn-network:
        ipv4_address: 10.10.10.11

networks:
  main-network:
  vpn-network:
    ipam:
      driver: default
      config:
        - subnet: 10.10.10.0/24