version: "3.7"
services:
  api:
    build:
      context: api
    ports:
      - 80:80
    volumes:
      - type: bind
        source: ${PWD}/api
        target: /api
    environment:
      - REDIS_PASS=$REDIS_PASS
      - MONGODB_USER=$MONGODB_USER
      - MONGODB_PASS=$MONGODB_PASS
    networks:
      main-network:

  create_data:
    build:
      context: utils
    environment:
      - MONGODB_USER=$MONGODB_USER
      - MONGODB_PASS=$MONGODB_PASS
    command: python3 generate_test_data.py --create
    depends_on:
      - mongodb
      - api
    networks:
      main-network:

  mongodb:
    image: mongo:4.4.1
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGODB_USER
      MONGO_INITDB_ROOT_PASSWORD: $MONGODB_PASS
    networks:
      main-network:

networks:
  main-network: